### ISSUE TITLE
Page is rendered once without style on Firefox

### ISSUE THREAD

**Issue by erf** [ziglang/www.ziglang.org#144] opened 2021-09-02 14:50 UTC
Minor annoyance. I noticed the page is rendered once without style, before with style, which is is causing a flash of sorts. This happened on Firefox. I could not recreate it on Safari or Chrome. I'm on macOS.

**Comment by nektro** [comment] 2021-09-17 22:46
This is because Firefox much more eager about showing the user content than others and a good thing. This effect is very reproducible if you artificially slow your internet speed in dev tools as it is a result of the css being an "external" resource from the html of the page.

**Comment by erf** [comment] 2021-09-17 23:05
Hmm. Performance is good, but don't think the flashing is a good thing though. Could style not be preloaded before showing page?

**Comment by nektro** [comment] 2021-09-17 23:56
the browser is not able to determine that the css even exists until it reaches the `<link>` tag

**Comment by erf** [comment] 2021-09-18 08:28
but the link tag / css is loaded before the body, no?

**Comment by nektro** [comment] 2021-09-18 08:43
no

**Comment by erf** [comment] 2021-09-18 09:32
I guess it's an async operation to load the links and you would hook on to a callback when everything is loaded and then render the body with the correct style, but that is probably out of scope of hugo which is used here ..

**Comment by kristoff-it** [comment] 2024-09-19 14:00
Not sure if this is an issue with a specific page or all pages. I'd be happy to merge a patch that improves this as long as the change is not insanely convoluted (as sometimes solutions have to get to force a specific browser behavior). Closing in the meantime.

**Closed by kristoff-it** 2024-09-19 14:00 UTC
