### ISSUE TITLE
I searched for standard library function documentation in the docs and didn't find it

### ISSUE THREAD

**Issue by srb623** [ziglang/www.ziglang.org#22] opened 2018-10-03 07:04 UTC
I am totally new to zig and read your document on the language and found it helpful.  It enabled me to make a start on learning the language.  However I could not find any documentation on the functions in the zig standard library.  I realise that I can read the code but when you have just read the language manual today, expecting one to read the code is a little bit much.  Can somebody please work on providing some links to the main language reference manual to documentation on the entire standard library ?  This would be enormously helpful and I think it would also help more people get interested in learning the language.  I have just downloaded and installed version 0.3 of the zig language.

**Comment by hspak** [comment] 2019-06-30 00:29
Helpful docs in the meantime: https://github.com/ziglang/zig/wiki/FAQ#where-is-the-documentation-for-the-zig-standard-library

**Comment by Mouvedia** [comment] 2020-09-19 17:17
dupe of #14

**Comment by kristoff-it** [comment] 2020-10-26 16:11
See my reply in #14

**Closed by kristoff-it** 2020-10-26 16:11 UTC
