### ISSUE TITLE
Broken links in the Overview page

### ISSUE THREAD

**Issue by Shanks512** [ziglang/www.ziglang.org#191] opened 2022-03-16 08:42 UTC
Couple of broken links in this section: https://ziglang.org/learn/overview/#cross-compiling-is-a-first-class-use-case

Namely,
- https://ziglang.org/learn/overview/#support-table
- https://ziglang.org/learn/overview/#tier-3-support

**Comment by perillo** [comment] 2022-04-17 09:34
The support table is now only available in release notes: https://ziglang.org/learn/overview/#wide-range-of-targets-supported.

The problem is that the document is using an old release (0.8.0).
The links should be automatically updated at each new release.

**Comment by llimllib** [comment] 2024-06-04 20:57
I came here to report this as well. It's pretty confusing to new users that all the support table links are broken!

**Comment by kristoff-it** [comment] 2024-09-19 14:35
dupe of #100

**Closed by kristoff-it** 2024-09-19 14:35 UTC
