### ISSUE TITLE
Example on homepage does not appear to work

### ISSUE THREAD

**Issue by ClaudioAlbertin** [ziglang/www.ziglang.org#268] opened 2023-07-04 22:56 UTC
The following is code taken directly from the current Zig homepage:

```zig
const std = @import("std");
const parseInt = std.fmt.parseInt;

test "parse integers" {
    const input = "123 67 89,99";
    const ally = std.testing.allocator;

    var list = std.ArrayList(u32).init(ally);
    // Ensure the list is freed at scope exit.
    // Try commenting out this line!
    defer list.deinit();

    var it = std.mem.tokenize(u8, input, " ,");
    while (it.next()) |num| {
        const n = try parseInt(u32, num, 10);
        try list.append(n);
    }

    const expected = [_]u32{ 123, 67, 89, 99 };

    for (expected, list.items) |exp, actual| {
        try std.testing.expectEqual(exp, actual);
    }
}
```

However when executed as described, it produces the following error:
```
$ zig test parse_integers.zig
parse_integers.zig:21:18: error: expected ')', found ','
    for (expected, list.items) |exp, actual| {
                 ^
```

This is using the latest available version of Zig:
```
$ zig version
0.10.1
```

**Comment by nektro** [comment] 2023-07-04 23:31
Zig changes fairly rapidly and a new release is due very soon so the homepage example is designed to work with Zig master.

**Comment by andrewrk** [comment] 2023-07-26 02:19
duplicate of #252. the new version comes out on August 3

**Closed by andrewrk** 2023-07-26 02:19 UTC
